### ISSUE TITLE
Dependency import path updation

### ISSUE THREAD

**Issue by shammishailaj** [willscott/memphis#3]
Hi 

This issue is related to: [Go-NFS issue #9](https://github.com/willscott/go-nfs/issues/9)

In order to fix the following issue in [Go-NFS](https://github.com/willscott/go-nfs)

```go: github.com/willscott/go-nfs@v0.0.0-20201019040824-49fd33e9cb45 requires
	github.com/willscott/memphis@v0.0.0-20200912205913-768fef98189f requires
	go.polydawn.net/go-timeless-api@v0.0.0-00010101000000-000000000000: unrecognized import path "go.polydawn.net/go-timeless-api": https fetch: Get "https://go.polydawn.net/go-timeless-api?go-get=1": dial tcp 107.170.61.58:443: connect: connection refused
```

Please merge this PR [https://github.com/willscott/memphis/pull/2](https://github.com/willscott/memphis/pull/2)

**Comment by willscott** [comment]
Did this work for you? I get go errors being unhappy that the import path doesn't match - e.g. using the github path means that you end up using golang's selected version (the v0.0.0) of the polydawn import path which is internally used as the import within [rio/fs](https://github.com/polydawn/rio/blob/master/fs/walk.go#L6). You already have the pinned current version in your go.sum so you're okay on an existing repo, but re-running `go get` after this change will continue to fail is my guess.

**Comment by shammishailaj** [comment]
@willscott So I am not directly using this library. I just wanted to try out the [Go-NFS](https://github.com/willscott/go-nfs) project and this project is a requirement there. So, unless you merge my PR, I will not be able to check. 

I saw the issue with rio/fs. Will need to generate a PR for that as well.

**Comment by willscott** [comment]
I talked earlier this week with @warpfork, and got agreement to change the paths in rio to use github as the import path there so that the replace directives aren't needed and it can be used by go.mod style libraries. that'll fix this problem.

I expect to get a moment to work on that over the weekend.

**Comment by shammishailaj** [comment]
@willscott Forgot to mention that the changes I am pushing, did allow me to successfully execute a `go mod vendor` which was failing earlier due to the unresponsive host.

Also, I just tried checking connectivity to the domain: go.polydawn.net over ports 80, 443, and 22 out of which only 22 succeeded.

Also, I have created a repository to utilize your go-nfs library at: https://github.com/shammishailaj/osnfs

Clone it and run `go mod vendor` you will see the error.

**Comment by shammishailaj** [comment]
> I talked earlier this week with @warpfork, and got agreement to change the paths in rio to use github as the import path there so that the replace directives aren't needed and it can be used by go.mod style libraries. that'll fix this problem.
> 
> I expect to get a moment to work on that over the weekend.

Awesome! Thanks!
